# Site settings
title: Whit Kemmey
email: whit.kemmey@gmail.com
url: http://www.whitkemmey.com
description: "Whit Kemmey - Software Developer, Software Architect, and Systems Engineer"

# Contact form: comment the line below if you want to stick with the default PHP contact form
contact: static

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: 001d43
  secondary: c1ae78
  secondary-dark: 422600
#  primary: 827f72
#  secondary: ae560a
#  secondary-dark: 990000
#  primary: ae560a
#  secondary: 381813
#  secondary-dark: 333300
#  primary: 637c7a
#  secondary: b0566a
#  secondary-dark: 924351
#  primary: 80B3FF
#  secondary: FD6E8A
#  secondary-dark: A2122F
#  primary: 18bc9c
#  secondary: 2c3e50
#  secondary-dark: 233140

# Footer settings
footer:
  copyright: Whit Kemmey
  location: Location
  social: Around the Web
  credits: Credits

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: github
    url: http://github.com/wkemmey
  - title: twitter
    url: http://twitter.com/wkemmey
  - title: stack-overflow
    url: http://stackoverflow.com/users/716066/whit-kemmey
  - title: facebook
    url: https://www.facebook.com/whit.kemmey
  - title: linkedin
    url: https://www.linkedin.com/in/whitkemmey

# Postal address (add as many lines as necessary)
address:
  - line: Fredericksburg, VA 22408

# Credits content
credits: 'Generated with <a href="http://jekyllrb.com">Jekyll</a>, hosted by <a href="https://github.com">GitHub</a>, and styled with <a href="http://startbootstrap.com">Start Bootstrap</a>.'

# Build settings
markdown: kramdown
permalink: pretty
